### ISSUE TITLE
PyCall cells error with export github action

### ISSUE THREAD

**Issue by stefanbringuier** [JuliaPluto/static-export-template#10] opened 2022-05-03 05:11 UTC
I'm having issues with this github action during export of the notebooks that use [PyCall.jl](https://github.com/JuliaPy/PyCall.jl). I have the following in my notebooks:

![image](https://user-images.githubusercontent.com/2709082/166406131-b87893c9-e4a3-43af-a63f-dc3a0bcbcc1b.png)

and the notebooks run fine locally. However, upon pushing and github action for exporting the pluto notebooks I get pyimport errors. 

Here is an example error that uses [ScikitLearn.jl](https://github.com/cstjean/ScikitLearn.jl)[^a], It runs without issues on local Pluto session. PyCall related cells give:

![image](https://user-images.githubusercontent.com/2709082/166407027-7ee9e31a-dff3-42ea-b462-d1e58ef29d35.png)

[^a]: `ScikitLearn.jl` automatically uses `Conda.jl` to install `scikit-learn` so I don't really even need the `Conda` and `PyCall` cell. If I remove them still get same error.

**Comment by fonsp** [comment] 2022-05-10 13:04
Hi! When a notebook works on your computer, but not on the static export, then this is a *reproducibility problem*: the notebook is not guaranteed to work on its own.

Julia code that uses PyCall.jl will take some extra work before it is *reproducible*, because it depends on a global installation of python + packages. You could extra commands to your https://github.com/JuliaPluto/static-export-template/blob/main/.github/workflows/ExportPluto.yaml file to install the python dependencies, but then other people might not be able to run your notebook.

Alternatively, take a look at https://github.com/cjdoris/PythonCall.jl, a new alternative to PyCall, which makes reproducibility much easier.

**Comment by fonsp** [comment] 2022-05-10 13:04
I'm going to close this, but feel free to continue posting if you have more questions, or if you found a solution.

**Closed by fonsp** 2022-05-10 13:05 UTC
